### PR TITLE
Add a setting to use the sandbox site at https://sandbox.2checkout.com/

### PR DESCRIPTION
**Pull request by jackbravo**

### CODE REVIEW

**Comment by jackbravo** [comment]
The big downside that I see to the sandbox is that it ignores the `x_receipt_link_url` parameter, so there is no way to know in drupal if you paid or not:

http://help.2checkout.com/articles/FAQ/Can-I-specify-the-return-URL-on-the-fly/

**Comment by craigchristenson** [comment]
Let me take that one, I'll pull in the PR after I have fixed that silly limitation.

**Comment by jackbravo** [comment]
Any luck?

**Comment by craigchristenson** [comment]
Yup, I'll update the PR once it is released.

**Comment by jackbravo** [comment]
Great!

**Comment by craigchristenson** [comment]
Sandbox accounts can now define a site URL at signup. At this time existing sandbox account URLs cannot be altered by anyone except 2Checkout employees so you would need to open a support ticket or just signup for a new sandbox account and define your development website URL during signup.

**Comment by craigchristenson** [comment]
Thanks for your contribution, it is greatly appreciated.

**Pull request merged**
